# Generated by Django 3.2.25 on 2024-09-19 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('Products', 'Product')
    ]
